spring:
  # H2 DataBase 
  h2:
    console:
      enabled: true
      path: /console
  # JDBC
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

# Server port
server:
  port: 8991